TomaszMichalSzandalaLab5ASP/TomaszMichalSzandalaLab5ASP/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using TomaszMichalSzandalaLab5ASP.Models;

namespace TomaszMichalSzandalaLab5ASP.Controllers
{
    public class MoviesController : Controller
    {
        //
        // GET: /Movies/
        LibraryDBContext ldbcontext = new LibraryDBContext();


        public ActionResult Index()
        {

            var query = (from movie in ldbcontext.Movie select movie);
            return View(query.ToList());
        }
        public void DbInit()
        {
            ldbcontext.Movie.Add(new Movie() { Name = "Avengers", DateTime = DateTime.Now });
            ldbcontext.Movie.Add(new Movie() { Name = "Avengers 2", DateTime = DateTime.Now });
            ldbcontext.Movie.Add(new Movie() { Name = "Thor", DateTime = DateTime.Now });
            ldbcontext.Movie.Add(new Movie() { Name = "Thor 2", DateTime = DateTime.Now });
            ldbcontext.Movie.Add(new Movie() { Name = "Jamnik", DateTime = DateTime.Now });
            ldbcontext.Movie.Add(new Movie() { Name = "Pies", DateTime = DateTime.Now });
            ldbcontext.SaveChanges();
        }
        public ActionResult ShowAll()
        {
            var query = from movie in ldbcontext.Movie select movie;

            return View(query.ToList());
        }
        [HttpPost]
        public ActionResult AddNewMovie()
        {
            Movie _movie = new Movie();
            _movie.Name = "301";
            _movie.DateTime = DateTime.Now;
            ldbcontext.Movie.Add(_movie);
            ldbcontext.SaveChanges();

            return RedirectToAction("ShowAll");

        }
        [HttpPost]
        public string DeleteById(int movieId)
        {
            try
            {
                Movie movieToDelete = ldbcontext.Movie.Find(movieId);
                ldbcontext.Movie.Remove(movieToDelete);
                ldbcontext.SaveChanges();
            }
            catch (Exception exp)
            {
                return exp.Message;
            }

            return "0";

        }
       public ActionResult UpdateById(int id)
        {
            var query = from movie in ldbcontext.Movie select movie;

            return View("UpdateById");
        }
       [HttpPost]
       public ActionResult SaveChanges(Movie newMovieData)
       {
           Movie movie = ldbcontext.Movie.Find(newMovieData.ID);
           movie.Name = newMovieData.Name;

           movie.DateTime = newMovieData.DateTime;

           ldbcontext.SaveChanges();

           return RedirectToAction("ShowAll");

       }
    }
}
   
/*
 * 0-wyświtlić w tabeli
 * 1-Pizza Menu Tworzenie włąsnej pizzy
 * 
 */

TomaszMichalSzandalaLab5ASP/TomaszMichalSzandalaLab5ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/jquery")
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrap.css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("MOVIE", "ShowAll", "Movies")</li>
                            <li>@Html.ActionLink("index", "Index", "Movies")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>


        @RenderSection("scripts", required: false)
    </body>
</html>